### PR TITLE
Add more customisation to the slider

### PR DESCRIPTION
**Pull request by AlexanderMarchant**

### CODE REVIEW

**Comment by AlexMarchant98** [comment]
The final change results in the setMinMax function being made private and a new function 'setInitialMinMax' taking its place.

**Comment by nanjingboy** [comment]
Thanks！

**Comment by nanjingboy** [comment]
@AlexMarchant98 I'm sorry, but can you tell me why you add `maxSliderValue` and `maxValueAppendedString`  config ?

**Comment by nanjingboy** [comment]
@AlexMarchant98  I think the `labelsPreprendedString` is not necessary, you can do it like this https://github.com/nanjingboy/ZMSwiftRangeSlider/blob/revert-11-master/Example/Example/ViewController.swift#L17-L22

**Comment by nanjingboy** [comment]
@AlexMarchant98 I release the new version with the `labelsAreBelow` configuration，the `labelsFont` is duplicate with `displayTextFontSize` 。

**Comment by AlexMarchant98** [comment]
> @AlexMarchant98 I'm sorry, but can you tell me why you add `maxSliderValue` and `maxValueAppendedString` config ?


maxSliderValue - Used to store the maxValue initially set by the user as I could not see a place where this value was stored

maxValueAppendedString - If the maxValue is hit, you can use this to append a string, that indiciates something greater.

In my case, I am using it as a price range sldier:

prependedString = "£"
maxSliderValue = 100
maxValueAppendedString = "+"

When the maxValue != maxValueSlider I want it to display **£**(maxValue)
When the maxValue == maxSliderValue I want it to display **£**(maxValue)**+**

Simulator Screen Shot - iPhone 11 - 2020-06-18 at 07 00 30


Simulator Screen Shot - iPhone 11 - 2020-06-18 at 07 00 34

**Comment by nanjingboy** [comment]
I think you can implement it like this https://github.com/nanjingboy/ZMSwiftRangeSlider/blob/master/Example/Example/ViewController.swift#L17-L22

**Pull request merged**
